# Generated by Django 2.1.7 on 2019-03-26 07:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('t_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ttype', models.CharField(default='Incident', max_length=50)),
                ('category', models.CharField(default='Other', max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('priority', models.CharField(default='Normal', max_length=10)),
                ('status', models.CharField(default='Open', max_length=20)),
                ('requestuser', models.CharField(default='System Admin', max_length=50)),
                ('processmanager', models.CharField(default='System Admin', max_length=50)),
            ],
        ),
    ]
